# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3355916869bcc00d6365091f109a360f"
name = "EA_AMINO"
handle = "ea_amino"
application_url = "https://ec09-154-80-119-147.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "muscled-tests.myshopify.com"

include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_orders,write_orders,read_customers"

[auth]
redirect_urls = [
  "https://ec09-154-80-119-147.ngrok-free.app/auth/callback",
  "https://ec09-154-80-119-147.ngrok-free.app/auth/shopify/callback",
  "https://ec09-154-80-119-147.ngrok-free.app/api/auth/callback",
]
[app_proxy]
url = "https://ec09-154-80-119-147.ngrok-free.app/proxy/api"
subpath = "EA-api"
prefix = "a"

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
