# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "16132b6701eebe7d5f0dbf74043f3dbe"
name = "EA"
handle = "ea-1"
application_url = "https://cc59-115-186-141-30.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "muscled-tests.myshopify.com"

include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_inventory,write_customers,read_customers"

[auth]
redirect_urls = [
  "https://cc59-115-186-141-30.ngrok-free.app/auth/callback",
  "https://cc59-115-186-141-30.ngrok-free.app/auth/shopify/callback",
  "https://cc59-115-186-141-30.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
