# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "675cb2b815a5b177ce4e6ca87a71d47c"
name = "BrightLink"
handle = "bright-link"
application_url = "https://2ef4-223-123-19-237.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "muscled-tests.myshopify.com"

include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_inventory,write_customers,read_customers"

[auth]
redirect_urls = [
  "https://2ef4-223-123-19-237.ngrok-free.app/auth/callback",
  "https://2ef4-223-123-19-237.ngrok-free.app/auth/shopify/callback",
  "https://2ef4-223-123-19-237.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
